"""university_new_fields_pending_registrations

Revision ID: cde25636653f
Revises: 30ff2f9744ca
Create Date: 2026-08-11 01:35:52.866791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde25636653f'
down_revision: Union[str, Sequence[str], None] = '30ff2f9744ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure the PostgreSQL ENUM type exists before adding the column
    institutiontype = sa.Enum(
        'UNIVERSITY', 'POLYTECHNIC', 'COLLEGE', 'PROFESSIONAL', 'VOCATIONAL', 'OTHER',
        name='institutiontype'
    )
    institutiontype.create(op.get_bind(), checkfirst=True)

    # Add the column as nullable, populate existing rows, then enforce NOT NULL
    op.add_column('university_registry', sa.Column('institution_type', institutiontype, nullable=True))

    # Populate existing rows with a safe default so the NOT NULL constraint can be applied
    op.execute("UPDATE university_registry SET institution_type = 'OTHER' WHERE institution_type IS NULL")

    # Now alter the column to be NOT NULL
    op.alter_column('university_registry', 'institution_type', nullable=False)
    op.add_column('university_registry', sa.Column('official_email', sa.String(length=255), nullable=True))
    op.add_column('university_registry', sa.Column('phone', sa.String(length=60), nullable=True))
    op.add_column('university_registry', sa.Column('website_url', sa.String(length=255), nullable=True))
    op.add_column('university_registry', sa.Column('year_established', sa.Integer(), nullable=True))
    op.add_column('university_registry', sa.Column('student_population', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_university_registry_university_code'), table_name='university_registry')
    op.create_unique_constraint(None, 'university_registry', ['university_code'])
    op.drop_column('university_registry', 'contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university_registry', sa.Column('contact', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'university_registry', type_='unique')
    op.create_index(op.f('ix_university_registry_university_code'), 'university_registry', ['university_code'], unique=True)
    op.drop_column('university_registry', 'student_population')
    op.drop_column('university_registry', 'year_established')
    op.drop_column('university_registry', 'website_url')
    op.drop_column('university_registry', 'phone')
    op.drop_column('university_registry', 'official_email')
    op.drop_column('university_registry', 'institution_type')
    # Drop the ENUM type if it exists
    institutiontype = sa.Enum(name='institutiontype')
    institutiontype.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
